# Branch-Pruner-Default | GitHub Action Workflow
# 
# Description: Truncates the old commit history of a selected target branch
# Author: Sitdisch
# Source: https://github.com/myactionway/branch-pruner-workflows
# License: MIT
# Copyright (c) 2021 Sitdisch
# 
# CAUTION: IT IS A POWERFUL TOOL AND YOU USE IT AT YOUR OWN RISK. CUTS CAN'T BE UNDONE.

name: 'Branch-Pruner-Default'

########################################################################
# DEFINE YOUR INPUTS AND TRIGGERS IN THE FOLLOWING
########################################################################

# INPUTS as environmental variables (env) for not manually triggered workflows 
env:
  NEW_FIRST_COMMIT: HEAD~36 # e.g. commit-hash or HEAD~N etc.
  TOKEN_NAME: 'SITDISCH_WORKFLOW_REPO_TOKEN' # target token name; insert only the name never the real value e.g. 'BRANCH_PRUNER_TOKEN'
  # If any of the following env is blank, a default value is used instead
  REPOSITORY: # target repository e.g. 'dummy/mytargetrepo'
  BRANCH: # branch to be pruned e.g 'master'
  USER_NAME: # user who should commit e.g. 'dummy'
  USER_EMAIL: # e.g. 'dummy@gmail.com'
  # 
  # THAT'S IT; JUMP TO THE TRIGGERS;
  DEFAULT_REPOSITORY: ${{ github.repository }} # repo with this file
  DEFAULT_BRANCH: 'master'
  DEFAULT_USER_NAME: 'github-actions[bot]'
  DEFAULT_USER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'

# TRIGGERS
on:
  # push:
  schedule: # Check your schedule here => https://crontab.guru/
    - cron: '00 00 01 * *' # e.g. every first day of a month at 00:00
  # 
  # THAT'S IT; YOU'RE DONE;
  workflow_dispatch:
    inputs:
      new_first_commit:
        description: 'New first commit'
        required: true
      token_name:
        description: 'Target token name (NO VALUE!)'
        required: true
      repository:
        description: 'Target repository'
        required: true
      branch:
        description: 'Branch to be pruned'
        required: true
        default: 'master'
      user_name:
        description: 'User who should commit'
        required: true
        default: 'github-actions[bot]'
      user_email:
        description: 'User e-mail address'
        required: true
        default: '41898282+github-actions[bot]@users.noreply.github.com'

########################################################################
# THAT'S IT; YOU DON'T HAVE TO DEFINE ANYTHING IN THE FOLLOWING
########################################################################

jobs:
  branch-pruner-default:
    runs-on: ubuntu-22.04
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repository || env.REPOSITORY || env.DEFAULT_REPOSITORY }}
          token: ${{ secrets[github.event.inputs.token_name] || secrets[env.TOKEN_NAME] }}
          fetch-depth: '0'
          ref: ${{ github.event.inputs.branch || env.BRANCH || env.DEFAULT_BRANCH }}
      - uses: myactionway/branch-pruner-action@v2.0
        with:
          new_first_commit: ${{ github.event.inputs.new_first_commit || env.NEW_FIRST_COMMIT }}
          branch: ${{ github.event.inputs.branch || env.BRANCH || env.DEFAULT_BRANCH }}
          user_name: ${{ github.event.inputs.user_name || env.USER_NAME || env.DEFAULT_USER_NAME }}
          user_email: ${{ github.event.inputs.user_email || env.USER_EMAIL || env.DEFAULT_USER_EMAIL }}
